var modules =
[
    [ "SAI - Entry point specific API definitions.", "group__SAI.html", "group__SAI" ],
    [ "SAI - ACL specific API definitions", "group__SAIACL.html", "group__SAIACL" ],
    [ "SAI - Adaptive Routing and Switching specific API definitions", "group__SAIARS.html", "group__SAIARS" ],
    [ "SAI - ARS profile specific API definitions.", "group__SAIARSPROFILE.html", "group__SAIARSPROFILE" ],
    [ "SAI - BFD specific public APIs and data structures", "group__SAIBFD.html", "group__SAIBFD" ],
    [ "SAI - Bridge specific API definitions", "group__SAIBRIDGE.html", "group__SAIBRIDGE" ],
    [ "SAI - Buffer specific API definitions", "group__SAIBUFFER.html", "group__SAIBUFFER" ],
    [ "SAI - Counter specific API definitions", "group__SAICOUNTER.html", "group__SAICOUNTER" ],
    [ "SAI - Debug counter specific API definitions", "group__SAIDEBUGCOUNTER.html", "group__SAIDEBUGCOUNTER" ],
    [ "SAI - DTEL specific API definitions", "group__SAIDTEL.html", "group__SAIDTEL" ],
    [ "SAI - FDB specific API definitions", "group__SAIFDB.html", "group__SAIFDB" ],
    [ "SAI - GPE specific API definitions", "group__SAIGENERICPROGRAMMABLE.html", "group__SAIGENERICPROGRAMMABLE" ],
    [ "SAI - Hash specific API definitions.", "group__SAIHASH.html", "group__SAIHASH" ],
    [ "SAI - Host Interface specific API definitions", "group__SAIHOSTINTF.html", "group__SAIHOSTINTF" ],
    [ "SAI - ICMP_ECHO specific public APIs and data structures", "group__SAIICMPECHO.html", "group__SAIICMPECHO" ],
    [ "SAI - IPMC specific API definitions", "group__SAIIPMC.html", "group__SAIIPMC" ],
    [ "SAI - IPMC group specific API definitions", "group__SAIIPMCGROUP.html", "group__SAIIPMCGROUP" ],
    [ "SAI - IPsec specific API definitions", "group__SAIIPSEC.html", "group__SAIIPSEC" ],
    [ "SAI - Isolation group specific API definitions", "group__SAIISOLATIONGROUP.html", "group__SAIISOLATIONGROUP" ],
    [ "SAI - L2MC specific API definitions", "group__SAIL2MC.html", "group__SAIL2MC" ],
    [ "SAI - L2MC group specific API definitions", "group__SAIL2MCGROUP.html", "group__SAIL2MCGROUP" ],
    [ "SAI - LAG specific API definitions", "group__SAILAG.html", "group__SAILAG" ],
    [ "SAI - MACsec specific API definitions", "group__SAIMACSEC.html", "group__SAIMACSEC" ],
    [ "SAI - Multicast FDB specific API definitions", "group__SAIMCFDB.html", "group__SAIMCFDB" ],
    [ "SAI - Mirror specific public APIs and data structures", "group__SAIMIRROR.html", "group__SAIMIRROR" ],
    [ "SAI - MPLS specific API definitions", "group__SAIMPLS.html", "group__SAIMPLS" ],
    [ "SAI - Network Address Translation (NAT) specific API definitions", "group__SAINAT.html", "group__SAINAT" ],
    [ "SAI - Neighbor specific API definitions.", "group__SAINEIGHBOR.html", "group__SAINEIGHBOR" ],
    [ "SAI - Next hop specific API definitions.", "group__SAINEXTHOP.html", "group__SAINEXTHOP" ],
    [ "SAI - Next hop group specific API definitions", "group__SAINEXTHOPGROUP.html", "group__SAINEXTHOPGROUP" ],
    [ "SAI - Object API definitions.", "group__SAIOBJECT.html", "group__SAIOBJECT" ],
    [ "SAI - QOS Policer specific API definitions", "group__SAIPOLICER.html", "group__SAIPOLICER" ],
    [ "SAI - Port specific API definitions", "group__SAIPORT.html", "group__SAIPORT" ],
    [ "SAI - Prefix Compression API definitions", "group__SAIPREFIXCOMPRESSION.html", "group__SAIPREFIXCOMPRESSION" ],
    [ "SAI - QOS Maps specific API definitions.", "group__SAIQOSMAPS.html", "group__SAIQOSMAPS" ],
    [ "SAI - QOS Queue specific API definitions.", "group__SAIQUEUE.html", "group__SAIQUEUE" ],
    [ "SAI - Route specific API definitions", "group__SAIROUTE.html", "group__SAIROUTE" ],
    [ "SAI - Router interface specific API definitions", "group__SAIROUTERINTF.html", "group__SAIROUTERINTF" ],
    [ "SAI - RPF group specific API definitions", "group__SAIRPFGROUP.html", "group__SAIRPFGROUP" ],
    [ "SAI - Samplepacket specific public APIs and data structures", "group__SAISAMPLEPACKET.html", "group__SAISAMPLEPACKET" ],
    [ "SAI - QOS scheduler specific API definitions", "group__SAISCHEDULER.html", "group__SAISCHEDULER" ],
    [ "SAI - QOS scheduler group specific API definitions", "group__SAISCHEDULERGROUP.html", "group__SAISCHEDULERGROUP" ],
    [ "SAI - SRV6 specific API definitions", "group__SAISRV6.html", "group__SAISRV6" ],
    [ "SAI - Status codes definitions", "group__SAISTATUS.html", "group__SAISTATUS" ],
    [ "SAI - STP specific public APIs and data structures", "group__SAISTP.html", "group__SAISTP" ],
    [ "SAI - Switch specific API definitions", "group__SAISWITCH.html", "group__SAISWITCH" ],
    [ "SAI - SYNCE specific API definitions", "group__SAISYNCE.html", "group__SAISYNCE" ],
    [ "SAI - System Port specific API definitions", "group__SAISYSTEMPORT.html", "group__SAISYSTEMPORT" ],
    [ "SAI - Telemetry and monitoring specific API definitions", "group__SAITAM.html", "group__SAITAM" ],
    [ "SAI - Next hop specific API definitions", "group__SAITUNNEL.html", "group__SAITUNNEL" ],
    [ "SAI - Two-Way Active Measurement Protocol specific public APIs and data structures", "group__SAITWAMP.html", "group__SAITWAMP" ],
    [ "SAI - Types definitions", "group__SAITYPES.html", "group__SAITYPES" ],
    [ "SAI - User Defined Field specific API definitions", "group__SAIUDF.html", "group__SAIUDF" ],
    [ "SAI - Router specific API definitions", "group__SAIROUTER.html", "group__SAIROUTER" ],
    [ "SAI - VLAN specific API definitions", "group__SAIVLAN.html", "group__SAIVLAN" ],
    [ "SAI - QOS WRED specific API definitions", "group__SAIWRED.html", "group__SAIWRED" ],
    [ "SAI - Experimental: BMTOR specific API definitions", "group__SAIEXPERIMENTALBMTOR.html", "group__SAIEXPERIMENTALBMTOR" ],
    [ "SAI - Experimental: DASH ACL specific API definitions", "group__SAIEXPERIMENTALDASHACL.html", "group__SAIEXPERIMENTALDASHACL" ],
    [ "SAI - Experimental: DASH appliance specific API definitions", "group__SAIEXPERIMENTALDASHAPPLIANCE.html", "group__SAIEXPERIMENTALDASHAPPLIANCE" ],
    [ "SAI - Experimental: DASH direction lookup specific API definitions", "group__SAIEXPERIMENTALDASHDIRECTIONLOOKUP.html", "group__SAIEXPERIMENTALDASHDIRECTIONLOOKUP" ],
    [ "SAI - Experimental: DASH ENI specific API definitions", "group__SAIEXPERIMENTALDASHENI.html", "group__SAIEXPERIMENTALDASHENI" ],
    [ "SAI - Experimental: DASH flow specific API definitions", "group__SAIEXPERIMENTALDASHFLOW.html", "group__SAIEXPERIMENTALDASHFLOW" ],
    [ "SAI - Experimental: DASH HA specific API definitions", "group__SAIEXPERIMENTALDASHHA.html", "group__SAIEXPERIMENTALDASHHA" ],
    [ "SAI - Experimental: DASH inbound routing specific API definitions", "group__SAIEXPERIMENTALDASHINBOUNDROUTING.html", "group__SAIEXPERIMENTALDASHINBOUNDROUTING" ],
    [ "SAI - Experimental: DASH meter specific API definitions", "group__SAIEXPERIMENTALDASHMETER.html", "group__SAIEXPERIMENTALDASHMETER" ],
    [ "SAI - Experimental: DASH outbound CA to PA specific API definitions", "group__SAIEXPERIMENTALDASHOUTBOUNDCATOPA.html", "group__SAIEXPERIMENTALDASHOUTBOUNDCATOPA" ],
    [ "SAI - Experimental: DASH outbound port map specific API definitions", "group__SAIEXPERIMENTALDASHOUTBOUNDPORTMAP.html", "group__SAIEXPERIMENTALDASHOUTBOUNDPORTMAP" ],
    [ "SAI - Experimental: DASH outbound routing specific API definitions", "group__SAIEXPERIMENTALDASHOUTBOUNDROUTING.html", "group__SAIEXPERIMENTALDASHOUTBOUNDROUTING" ],
    [ "SAI - Experimental: DASH PA validation specific API definitions", "group__SAIEXPERIMENTALDASHPAVALIDATION.html", "group__SAIEXPERIMENTALDASHPAVALIDATION" ],
    [ "SAI - Experimental: DASH trusted VNI specific API definitions", "group__SAIEXPERIMENTALDASHTRUSTEDVNI.html", "group__SAIEXPERIMENTALDASHTRUSTEDVNI" ],
    [ "SAI - Experimental: DASH tunnel specific API definitions", "group__SAIEXPERIMENTALDASHTUNNEL.html", "group__SAIEXPERIMENTALDASHTUNNEL" ],
    [ "SAI - Experimental: DASH VIP specific API definitions", "group__SAIEXPERIMENTALDASHVIP.html", "group__SAIEXPERIMENTALDASHVIP" ],
    [ "SAI - Experimental: DASH VNET specific API definitions", "group__SAIEXPERIMENTALDASHVNET.html", "group__SAIEXPERIMENTALDASHVNET" ],
    [ "SAI - Metadata Types Definitions", "group__SAIMETADATATYPES.html", "group__SAIMETADATATYPES" ],
    [ "SAI - Metadata Utilities Definitions", "group__SAIMETADATAUTILS.html", "group__SAIMETADATAUTILS" ],
    [ "SAI - Metadata Logger Definitions", "group__SAIMETADATALOGGER.html", "group__SAIMETADATALOGGER" ],
    [ "SAI - Serialize Definitions", "group__SAISERIALIZE.html", "group__SAISERIALIZE" ]
];